name: rust-analyzer
base: core18
adopt-info: rust-analyzer
architectures: [amd64, i386]
summary: An experimental Rust compiler front-end for IDEs 
description: |
    rust-analyzer is an experimental modular compiler frontend for the Rust language. It is a part of a larger rls-2.0 effort to create excellent IDE support for Rust.
grade: stable 
confinement: strict 

parts:
    rust-analyzer:
        plugin: rust
        source: https://github.com/rust-analyzer/rust-analyzer.git
        build-packages:
            - gcc-multilib
            - python-setuptools
        stage-packages:
            - cargo
            - rust-src
            - zlib1g
            - libgcrypt20
            - libgpg-error0
            - libstdc++6
            - libpcre3
        override-pull: |
            snapcraftctl pull
            dow=$(date +%u)
            if [ $dow == 4]; then
                git_ver=$(git tag --sort=taggerdate | grep -P "20[0-9]{2}-[0-9]{1,2}-[0-9]{1,2}" | tail -1)
                git checkout $git_ver
                snapcraftctl set-grade candidate
                snapcraftctl set-version $git_ver
            else
                snapcraftctl set-version "$(git describe --tags --always)"
            fi

plugs:
    dot-cargo:
        interface: personal-files
        read: 
        - $HOME/.cargo
apps:
    rust-analyzer:
        command: ./bin/rust-analyzer
        plugs:
            - home
            - network
            - dot-cargo
