name: rust-analyzer
base: core18
adopt-info: rust-analyzer
architectures: [amd64, i386]
summary: An experimental Rust compiler front-end for IDEs 
description: |
    rust-analyzer is an experimental modular compiler frontend for the Rust language. It is a part of a larger rls-2.0 effort to create excellent IDE support for Rust.
grade: stable 
confinement: strict 

parts:
    rust-analyzer:
        plugin: rust
        source: https://github.com/rust-analyzer/rust-analyzer.git
        build-packages:
            - gcc-multilib
            - python-setuptools
        stage-packages:
            - cargo
            - rust-src
            - zlib1g
            - libgcrypt20
            - libgpg-error0
            - libstdc++6
            - libpcre3
        override-pull: |
            snapcraftctl pull
            snapcraftctl set-version "$(git describe --tags --always)"

apps:
    rust-analyzer:
        command: ./bin/rust-analyzer --no-sysroot
        plugs:
            - home
            - network
